### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by djdiablo** [Elfocrash/L2jRoboto#6]
dec 11, 2017 12:09:00 AM net.sf.l2j.gameserver.network.clientpackets.L2GameClientPacket run
SEVERE: Client: [Character: 1 - Account: 1 - IP: 127.0.0.1] - Failed reading: [C] Action ; java.lang.NullPointerException
java.lang.NullPointerException
	at net.sf.l2j.gameserver.handler.admincommandhandlers.AdminEditChar.gatherCharacterInfo(AdminEditChar.java:696)
	at net.sf.l2j.gameserver.handler.admincommandhandlers.AdminEditChar.showCharacterInfo(AdminEditChar.java:685)
	at net.sf.l2j.gameserver.model.actor.instance.Player.onActionShift(Player.java:2869)
	at net.sf.l2j.gameserver.network.clientpackets.Action.runImpl(Action.java:54)
	at net.sf.l2j.gameserver.network.clientpackets.L2GameClientPacket.run(L2GameClientPacket.java:50)
	at net.sf.l2j.gameserver.network.L2GameClient.run(L2GameClient.java:755)
	at net.sf.l2j.commons.concurrent.ThreadPool$TaskWrapper.run(ThreadPool.java:248)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by Elfocrash** [comment]
This is known. It is no important so i won't be fixing it any time soon.
